name: CI-dockers

on: [push, pull_request]

jobs:
  build_test_docker:
    name: Build & Test the project
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: [centos7]
    
    steps:
      - uses: actions/checkout@master
      - name: Build Docker image
        uses: actions/docker/cli@master
        with:
            args: build -file .docker/Dockerfile.${{ matrix.distro }} -t ci-proj-${{ github.sha }}:latest .

      - name: Running project build
        uses: actions/docker/cli@master
        with:
            args: run ci-proj-${{ github.sha }}:latest ls -al /proj
