name: CI-dockers

on: [push, pull_request]

jobs:
  build_test_docker:
    name: Build & Test the project
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: [centos7]
    
    steps:
      - uses: actions/checkout@master
      - name: Build container image
        uses: actions/docker/cli@master
        with:
            args: build -f .docker/Dockerfile.${{ matrix.distro }} -t ci-proj-${{ github.sha }}:latest .

      - name: Build project in container
        uses: actions/docker/cli@master
        with:
            args: run ci-proj-${{ github.sha }}:latest cd /proj/.ci/build_project.sh

      - name: Test project in container
        uses: actions/docker/cli@master
        with:
            args: run ci-proj-${{ github.sha }}:latest cd /proj/.ci/test_project.sh
