name: CI-dockers

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: [.ci/Dockerfile.centos7]
    
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Build docker for ${{ matrix.file }}
        uses: ./.github/actions/run-in-docker
            with:
                file: ${{ matrix.file }}
                myargs: pwd
      -   
        name: Running build
        run: |
            ls -al
            ./autogen.sh
            ./configure --prefix=$PWD/install
            make all
            make install
