name: CI-dockers

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: [centos7]
    
    steps:
      - uses: actions/checkout@v1
      - name: Build Docker image
        uses: actions/docker/cli@master
        with:
          args: >
              build . \
              --build-arg VCS_REF=${{ github.sha }} \
              --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
              --file .ci/Dockerfile.${{ matrix.distro }} \
              --tag test

      - name: Running project build
        uses: actions/docker/cli@master
        with:
            args: run --rm test ./autogen.sh
