name: CI-dockers

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dfile: [.ci/Dockerfile.centos7]
    
    steps:
    - name: Run in docker
    - uses: actions/checkout@v1
    - uses: ./.github/actions/run-in-docker
      with:
        file: ${{ matrix.dfile }}
        myargs: pwd
        
    - name: test
      run: hostname
      
    - name: OS ${{ matrix.dfile }}
      run: |
        ./autogen.sh
        ./configure --prefix=$PWD/install
        make all
        make install
